### ISSUE TITLE
Blob upload might require specific roles per environment

### ISSUE THREAD

**Issue by mkennten** [paulmsft/ai-102-examples#7]
When the post-provisioning script runs the blobs cannot be uploaded to the storage account blob containers due to missing permissions.

![image](https://github.com/user-attachments/assets/4449f10d-48d4-4899-a666-3a69aa6c9915)

When adding for example "Storage Blob Data Contributor" it works. Since my account is the owner of the storage account, I'm not sure if this is either a prereq of the az storage command or a limitation of my subscription.

**Comment by paul-iveylabs** [comment]
@mkennten Thanks for this! Can you please fetch and try again from the `storage-contributor` branch before I open a PR? 😊 Looks like it did the job, plus I've added a storage account and option to upload RAG files for the AOAI demo
